/* blog-chunk5.js — blog batch 5 (2026-07-21 competitor-research pass):
 * 27 apps x 5 posts each, generated by build.js section 7b from product data.
 * Same drop-in convention as blog-chunk3.js. */
module.exports = [
  'bravowall', 'hawkwatch', 'postbird', 'castport', 'inkpress', 'feedloft',
  'reelsnag', 'voicebarn', 'droplink', 'snipvault', 'textract', 'signboard',
  'serpdeck', 'chatterbox', 'doortracker', 'famping', 'renewcheck', 'iconforge',
  'deskly', 'upkeepstatus', 'docsmithapi', 'vaultly', 'secretbox', 'certwatch',
  'resumecraft', 'pitchcraft', 'contractly',
];
