/* blog-chunk4.js — blog batch 4 (2026-07-21 competitor-research pass):
 * 28 apps x 5 posts each, generated by build.js section 7b from product data.
 * Same drop-in convention as blog-chunk3.js. */
module.exports = [
  'cutaway', 'whisperdesk', 'shrinkray', 'upwatch', 'trimly', 'billcraft',
  'bookslot', 'formforge', 'sigcraft', 'postdock', 'scantrail', 'cardsmith',
  'statfox', 'shipnotes', 'hearback', 'docwell', 'chatlet', 'boardly',
  'timevault', 'streakly', 'deepdesk', 'quillpad', 'pingcron', 'hookscope',
  'snapfleet', 'wrangle', 'vaultkeeper', 'queuecraft',
];
