/* blog-chunk6.js — blog batch 6 (2026-07-21 competitor-research pass):
 * 27 apps x 5 posts each, generated by build.js section 7b from product data.
 * Same drop-in convention as blog-chunk3.js. */
module.exports = [
  'captionly', 'utmcraft', 'reflink', 'starstack', 'clickmap', 'splitpoint',
  'hirestack', 'shiftly', 'rampcheck', 'punchcard', 'quizcraft', 'forumly',
  'roster', 'eventcraft', 'postcraft', 'slidecraft', 'redirectly', 'clientdesk',
  'pulsecheck', 'billoop', 'askback', 'citewatch', 'syncvault', 'voicebox',
  'quotewell', 'snapreceipt', 'remindly',
];
