/* blog-chunk3.js — first blog batch (2026-07-21 SEO pass): 18 apps, 5 posts
 * each, generated by build.js section 7b from each app's own product-data
 * object in src/products.js / src/products-51-100.js. Mirrors the existing
 * posts-1..6.js chunking convention used for /comparison/. To add the next
 * batch, drop a src/blog-chunk4.js with the same shape — no build.js edit
 * needed. */
module.exports = [
  'inkseal', 'keyloop', 'keymaster', 'ledgerlitehome', 'ledgerly', 'lessonforge',
  'linkguard', 'linkleaf', 'listcraft', 'logbin', 'maptrail', 'memeforge',
  'menuly', 'mockcraft', 'orgtree', 'overlayr', 'paletteforge', 'pdfsmith',
];
